service: aws-lambda-flask-template

frameworkVersion: "3"

custom:
  wsgi:
    app: app.app
    packRequirements: false

provider:
  name: aws
  runtime: python3.11

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-wsgi
  - serverless-python-requirements
